### ISSUE TITLE
better CSV utils

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/converter#4]
Since CSV is a common format for importing data (e.g. product data, contact lists, etc), I think we need to find some solid tools for this. We might even need to use a different lib for reading vs. writing (since exporting to CSV will also be common).

**Comment by doowb** [comment]
Do you mean finding a library other than `csv`, or find one that specializes in reading and another that specializes in writing? I think if we use the testing repo from #5 to determine how good `csv` is, then we can decide if we need to find another util. @hariadi might have some insights on this (I think he originally did the csv conversion code on this).

**Comment by jonschlinkert** [comment]
:+1: good call
